# Generated by Django 2.2.7 on 2020-01-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200130_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='image_small',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
