# Generated by Django 2.2.7 on 2020-01-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_itemimage_image_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_lower',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='name_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
