# Generated by Django 3.0.2 on 2020-02-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200216_1705'),
        ('item', '0007_auto_20200202_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fond',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Fond', verbose_name='Перечислить в фонд'),
        ),
        migrations.AddField(
            model_name='item',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='Отображается'),
        ),
    ]
