# Generated by Django 3.0.2 on 2020-02-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20200216_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='otherChoice',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативный выбор'),
        ),
        migrations.AlterField(
            model_name='item',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Отображается'),
        ),
    ]
