# Generated by Django 3.0.2 on 2020-03-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_auto_20200218_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isSold',
            field=models.BooleanField(default=False, verbose_name='Продан?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Отображается?'),
        ),
    ]
