# Generated by Django 3.0.2 on 2020-03-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sber_orderID',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sber_orderID'),
        ),
    ]
