# Generated by Django 3.0.2 on 2020-03-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_order_sber_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isService',
            field=models.BooleanField(default=False, verbose_name='Услуга?'),
        ),
    ]
