# Generated by Django 3.0.2 on 2020-02-15 14:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_fond'),
    ]

    operations = [
        migrations.AddField(
            model_name='fond',
            name='description_req',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='fond',
            name='deviz',
            field=models.CharField(db_index=True, editable=False, max_length=255, null=True, verbose_name='Девиз'),
        ),
    ]
