# Generated by Django 3.0.2 on 2020-02-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200215_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='fond',
            name='image_big',
            field=models.ImageField(blank=True, upload_to='fond/', verbose_name='Картинка на страницу фонда (1200х600)'),
        ),
    ]
