# Generated by Django 3.0.2 on 2020-02-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200216_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='fond',
            name='isOther',
            field=models.BooleanField(default=False, verbose_name='ИНОЕ???'),
        ),
    ]
