# Generated by Django 3.0.2 on 2020-03-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_fond_isother'),
    ]

    operations = [
        migrations.AddField(
            model_name='fond',
            name='money_earn',
            field=models.IntegerField(default=0, verbose_name='Перечислено в фонд'),
        ),
    ]
