# Generated by Django 3.0.2 on 2020-03-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_fond_money_earn'),
    ]

    operations = [
        migrations.AddField(
            model_name='fond',
            name='icon',
            field=models.ImageField(blank=True, upload_to='fond/', verbose_name='Иконка для главной'),
        ),
    ]
