# Generated by Django 3.0.2 on 2020-02-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_isread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='isRead',
        ),
        migrations.AddField(
            model_name='chat',
            name='isNewMessages',
            field=models.BooleanField(default=False, verbose_name='Есть новые сообщения'),
        ),
    ]
