# Generated by Django 3.0.2 on 2020-02-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200201_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isUnread',
            field=models.BooleanField(default=True, verbose_name='Не прочитанное сообщение'),
        ),
    ]
