# Generated by Django 3.0.2 on 2020-02-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_isunread'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='lastMessageOwn',
            field=models.BooleanField(default=False),
        ),
    ]
